/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 atom.gltf --transform
Author: AyeAyeCaptain (https://sketchfab.com/AyeAyeCaptain)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/atom-5843f1b624c4466ab2cff08a4d668a3b
Title: Atom
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/atom-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} position={[-52.5, -52.5, -52.5]} />
      </group>
    </group>
  )
}

useGLTF.preload('/atom-transformed.glb')
